name: auto update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
      - name: Install libvips
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips libvips-dev

      - name: Install uso-archive binary
        uses: baptiste0928/cargo-install@v2
        with:
          crate: uso-archive
          git: https://code.pepega.club/uso-archive/updater.git
          branch: main

      - name: Fetch updated IDs
        run: |
          date -uIs >./data/last-update.txt
          uso-archive fetch-ids --sorting updated --until-time "$(cat ./data/last-update.txt)" /tmp/ids.json

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download & Index
        run: |
          uso-archive download /tmp/ids.json ./data
          uso-archive index ./data ./data/search-index.json >/tmp/index.log || cat /tmp/index.log

      - name: Commmit & Push
        run: |
          git config user.name 'uso-archive[bot]'
          git config user.email '137587018+uso-archive[bot]@users.noreply.github.com'
          git add ./data
          uso-archive git-commit-msg ./data /tmp/ids.json | git commit -F -
          git rev-parse HEAD >./data/last-commit.txt
          git add ./data
          git commit -m "[*] update last-commit"
          git push
