name: SSH
on:
  workflow_dispatch:
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Debugging with ssh
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-actor: true
